#!/usr/bin/env bash
# Build the thesis PDF cleanly.
#
# Default mode: plain `tectonic main.tex` (no BibTeX involved because
# references.tex contains an inlined `\thebibliography` block already in
# citation-order. Clean, no warnings.)
#
# Regen mode (`./build.sh --regen-refs`): regenerate references.tex from
# references.bib via BibTeX. Use this whenever:
#   - you added/edited entries in references.bib
#   - you added a new \cite{...} in a chapter (and want the bibliography to
#     include it / renumber accordingly)
#
# Tectonic 0.15 has a known file-watcher bug that emits noisy "internal
# consistency problem when checking if main.bbl changed" warnings when it
# auto-detects BibTeX changes. We avoid that path by pre-baking the .bbl
# content into references.tex.

set -e
cd "$(dirname "$0")"

if [[ "$1" == "--regen-refs" ]]; then
  echo ">> Switching to BibTeX mode and rebuilding bibliography…"
  TMP_REFS=$(mktemp)
  cp references.tex "$TMP_REFS"

  cat > references.tex <<'EOF'
\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{References}
{\raggedright
\bibliographystyle{IEEEtran}
\bibliography{references}
}
EOF

  rm -f main.aux main.bbl main.blg main.toc main.lof main.lot main.out
  tectonic main.tex --reruns 3 --keep-intermediates >/dev/null 2>&1 || true

  if [[ ! -s main.bbl ]]; then
    echo "!! BibTeX failed — restoring previous references.tex"
    cp "$TMP_REFS" references.tex
    rm -f "$TMP_REFS"
    exit 1
  fi

  echo ">> Inlining new .bbl into references.tex…"
  {
    cat <<'EOF'
% References — inlined `\thebibliography` block in citation order.
% Generated by `./build.sh --regen-refs` from references.bib via BibTeX.
% Do not edit by hand; edit references.bib and re-run with --regen-refs.

\cleardoublepage
\phantomsection
\addcontentsline{toc}{chapter}{References}
{\raggedright
\renewcommand{\bibname}{References}

EOF
    cat main.bbl
    echo "}"
  } > references.tex

  rm -f "$TMP_REFS"
  echo ">> Done. references.tex regenerated."
  shift
fi

# Final compile. Tectonic 0.15 has a known quirk: it prints a "warning:"
# prefixed line for every (font, size) pair it loads — even when the font
# loads successfully. With newtxtext/newtxmath + many heading sizes, that
# floods the terminal with hundreds of harmless lines. We filter those out
# here so only real issues (Overfull/Underfull, missing references, undefined
# control sequences, etc.) are surfaced. PDF output is identical either way.
tectonic main.tex "$@" 2>&1 \
  | grep -vE '^warning:.*Requested font' \
  | grep -vE '^warning:[^:]*:[0-9]+:[[:space:]]*$' \
  | grep -vE '^warning: hyperref\.sty:[0-9]+:[[:space:]]+-> pzdr' \
  | grep -vE '^warning:.*-> (ptm|ntx|zptm|ms[ab]m|pzdr|lmmono|TeXGyre)' \
  | grep -vE '^Requested font ' \
  | grep -vE '^warning: warnings were issued by the TeX engine'
